[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['cd application && python manage.py collectstatic --noinput']

[start]
cmd = 'cd application && python manage.py migrate && gunicorn application.wsgi:application --bind 0.0.0.0:$PORT'